spring.application.name=spring-security
spring.security.user.name = sujal
spring.security.user.password =1234
server.servlet.session.cookie.same-site = strict

spring.datasource.url=jdbc:postgresql://localhost:5432/sujal
spring.datasource.username = postgres
spring.datasource.password = Sujal099


